### PR TITLE
Fix/133 report a problem component

### PR DESCRIPTION
**Pull request by Moro-Code**
# Description

This PR aims to fix issues with the Report a Problem button outlined in #42 

### Report a problem `<summary>` element
- [x] "Report a problem on this page"
- [x] Text should be centred
- [x] Text should be blue (like a link)
- [x] Cursor should be a `pointer` when hovered  
- [x] Active state should have a darker background
- [x] They are using `border-style: outset` to make it "pop"

### Groups of checkboxes 
- [x] Groups of related checkboxes / radio buttons should always be inside a `<fieldset>`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset
- [x] The "check all the issues" text should be the `<legend>` for the fieldset (so, inside of the `<form>`)

### Checkboxes
- [x] Let's make them 40 by 40px, not 44 by 44px
- [x] Remove 2px `top` and `left` CSS on input
- [x]  Set label:before `background` to `white`
- [x] Set label:after `height` to 13px

### Font sizing
- [x] 12px is way too small: let's set it to 16px again
- [x] Line height should be `1.4` or `1.5`
- [x] The "check all the issues" text at 18px is not enough contrast to 16px font, so increase it to 20 or 22px and increase the bottom margin a bit

### Width 
- [x] Setting 300px seems tight to me. Can we set a `max-width` of 350-400 somewhere (maybe 380?) and then `width: 100%` so that it will size down as needed.

## Test Instructions

1. Check storybooks to see if all items have been addressed 

## Checklist

- [x] Strings use placeholders for translation (No hard coded strings)
- [x] Unit tests have been added/updated

## Product and Sprint Backlog

[Trello](https://trello.com/b/ZqWtJSyh/alpha-site-board)

### CODE REVIEW

**Review by pcraig3 — CHANGES_REQUESTED** [review]
It's getting there. There are a few things that jump out at me.

- The font size on "report a problem" summary button seems too small. Can we make it 16px instead of 14?
- Let's make the background of the "questions" section the same colour and outline as the "summary" button. Right now the background is light blue for the questions, but on canada.ca both backgrounds are the same (or really close). You can see in the gif below.

### hover and active states 

| On Canada.ca | In this PR |
|---------|--------|
|      Screen Recording 2021-04-22 at 17 27 02    | Screen Recording 2021-04-22 at 17 26 09  |
|  when you click the button, you see an `:active` state, so the button gets darker than on hover. it also has a border surrounding it when the element is in `:focus`.   |    here we are missing a focus style and the active style. When you actually _click_ the button, you don't get a cool click interaction.    |

For the checkboxes, we are also missing focus and hover states.

| On Canada.ca | In this PR |
|---------|--------|
|   Screen Recording 2021-04-22 at 17 31 04   |  Screen Recording 2021-04-22 at 17 31 38     |
|  If you focus (tab + spacebar) [on the GDS ones](https://design-system.service.gov.uk/components/checkboxes/), you see a big yellow border. Same just after you click.  |  You can't see it, but the tab indicator disappears when you go into it. And when you click, there's no `:focus` styling.       |

**Comment by Moro-Code** [comment]
@pcraig3 will implement changes from the font but for the background colour in figma the colour is light blue. Im not sure which one I should follow

**Comment by stoltzf1** [comment]
Looks like this is the CSS from the Report a problem - Canada.ca design pattern (https://design.canada.ca/common-design-patterns/report-problem.html)

.well {
	min-height: 20px;
	padding: 19px;
	margin-bottom: 20px;
	background-color: #f5f5f5;
	border: 1px solid #e3e3e3;
	border-radius: 4px;
	-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.05);
	box-shadow: inset 0 1px 1px rgba(0,0,0,.05);
}

**Comment by pcraig3** [comment]
Okay @stoltzf1, so you think we should follow the Design System?

**Comment by Moro-Code** [comment]
fixes done.. review when you can @pcraig3

**Review by pcraig3 — APPROVED** [review]
Looks good!

**Pull request merged**
