### PR TITLE
Update signup page content

### PR DESCRIPTION
**Pull request by var-kyle**
# Description

[Content update - signup form edition](https://trello.com/c/SWSpQsId)

This PR updates the layout and content of the signup form. Unfortunately it required a new component so that's been bundled in here as well. I'm sorry this is so huge.

## Acceptance Criteria

The signup page matches what is in the designs.

## Test Instructions

1. Navigate to the signup form
2. Verify that the content/layout matches the designs in Figma

## Help Requested

- **There is something not working quite right with spacing in one checkbox lists - _please advise_**

## Checklist

- [x] Strings use placeholders for translation (No hard coded strings)
- [x] Unit tests have been added/updated

## Product and Sprint Backlog

[Trello](https://trello.com/b/ZqWtJSyh/alpha-site-board)

### CODE REVIEW

**Review by EphraimAssi — COMMENTED** [review]
Looks good! Only minor thing I saw is that in the Privacy Policy list, there was spacing between the list items in the Figma mock-up, the text was aligned together and not with the dot.

This is what we have right now:
image

This is what is in the mock-up:
image

**Review by will0684 — CHANGES_REQUESTED** [review]
Very thorough and well done Kyle 👍 besides what Ephraim mentioned, maybe we could use a little bit more margin beneath the labels on the form?

image

**Review by EphraimAssi — COMMENTED** [review]
Sorry I didn't explain well, only the first list has spacing the rest doesn't.
image

**Review by will0684 — DISMISSED** [review]
Looks awesome great work Kyle!

**Comment by will0684** [comment]
> Sorry I didn't explain well, only the first list has spacing the rest doesn't.
> image

Good call Ephraim I'll rescind my review.

**Review by EphraimAssi — APPROVED** [review]
Looks good!

**Pull request merged**
