### PR TITLE
Page title has been updated to describe the page to meet accessibility standards

### PR DESCRIPTION
**Pull request by DaceyTom2**
# Description

Page title has been updated to describe the page to meet accessibility standards

## Test Instructions

1. Navigate to /projects/virtual-assistant
2. Page title should be "Virtual Assistant Product Description" in English and "Description de l'assistant virtuel" in French
3. Page header should have remained the same

### CODE REVIEW

**Review by pcraig3 — COMMENTED** [review]
The convention is normally that the `<title>` is the same as the `<h1>`. Is there a reason to have them be different in this case?

**Comment by DaceyTom2** [comment]
Accessibility requested our title describe the page better. I'll reach out to our designer Hoy

**Comment by EphraimAssi** [comment]
I had to change the title tag because of analytics to keep everything consistent, sorry for the conflicting files.

**Comment by DaceyTom2** [comment]
This change isn't required as the accessibility check is already passing

**Pull request closed without merging**
