### PR TITLE
Projects page update

### PR DESCRIPTION
**Pull request by EphraimAssi**
# Description

[#372 Projects Page EN/FR](https://trello.com/c/nPtWq02t/372-372-projects-page-en-fr)

I updated the experiment page to project page. The cards are updated as well.
image
image

## Acceptance Criteria

Experiment cards should be 250px height for desktop and flexible height for mobile. Mobile cards should expand as needed based on content. The page should look like the new Figma design.

## Test Instructions

1. Run the code and check the project page
2. Compare it with Figma design

## Checklist

- [ ] Strings use placeholders for translation (No hard coded strings)
- [ ] Unit tests have been added/updated

## Product and Sprint Backlog

[Trello](https://trello.com/b/ZqWtJSyh/alpha-site-board)

### CODE REVIEW

**Comment by will0684** [comment]
@EphraimAssi any chance you could add a french translation value for this key into the french common translation file?

  "footerSocialMedia": "Social media",

**Comment by EphraimAssi** [comment]
I added a french key for the Social media link in the footer

**Comment by EphraimAssi** [comment]
I also updated the report a problem size since the new french text doesn't fit in

**Review by will0684 — APPROVED** [review]
Awesome work Ephraim 🚀

**Pull request merged**
