### PR TITLE
expand and collap state on checkbox

### PR DESCRIPTION
**Pull request by shawn320**
# Description

Added `aria-label` attribute on the checkbox on the Report A Problem form. The value of aria-label will either be `collapsed` or `expanded` depend on the state of the checkbox. By default, it's `collapsed`. When checkbox is checked, the value will be `expanded`

I tried to use `aria-expanded` at the beginning, but this attribute does not work on checkbox. I've tested it on different browser, but `aria-expanded` seems only work on buttons. The screen reader won't anounce it on checkbox.

## Test Instructions

Open the Report A Problem form on any pages. Test with screen reader

## Checklist

- [ ] Strings use placeholders for translation (No hard coded strings)
- [ ] Unit tests have been added/updated
- [x] Update CHANGELOG

## Product and Sprint Backlog

[Report A Problem Accessibility Update](https://jira-dev.bdm-dev.dts-stn.com/secure/RapidBoard.jspa?rapidView=96&projectKey=SCL&view=detail&selectedIssue=SCL-573)

### CODE REVIEW

**Review by var-kyle — CHANGES_REQUESTED** [review]
We want to use `aria-expanded` instead of `aria-label` in this situation. aria-label would just override the actual label and all a screen reader would say is "collapsed" or "expanded".

aria-expanded just has boolean values, so it should be `false` by default and then set to `true` when the checkbox is selected.

**Comment by var-kyle** [comment]
> We want to use `aria-expanded` instead of `aria-label` in this situation. aria-label would just override the actual label and all a screen reader would say is "collapsed" or "expanded".

My mistake, `aria-label` won't override the label, I was thinking of `aria-labelledby`

**Comment by shawn320** [comment]
> 

Made a small adjustment, instead of using `aria-label` which overrides the original label, I added a `sr-only` text under the label. The screen reader will anounce either `expanded` or `collapse` depends on the state change.

**Review by var-kyle — APPROVED** [review]
I would still prefer using `aria-expanded`, but it doesn't work with Mac's VoiceOver, so this is a good substitution. Thank you for all the testing to find that out @shawn320

**Pull request merged**
