### PR TITLE
Project page UI updates

### PR DESCRIPTION
**Pull request by var-kyle**
# Description

[Project page UI updates](https://trello.com/c/3Co8ZYK4)

Project label colours have been changed:
image

The filter buttons have been updated to accommodate mobile screens, though it's still off. 
image

## Acceptance Criteria

Project labels have updated colours and the filter bar fits mobile screen too.

## Test Instructions

1. Visit the projects page
2. Notice the new colours for project status
3. Change to mobile view
4. Notice that the filter bar doesn't get put on separate lines

## Help Requested

- The text in the filter bar is not centered vertically (for the "all" option). If anyone knows how to fix that, please help.

## Checklist

- [ ] Strings use placeholders for translation (No hard coded strings)
- [ ] Unit tests have been added/updated
- [x] Update CHANGELOG

## Product and Sprint Backlog

[Trello](https://trello.com/b/ZqWtJSyh/alpha-site-board)

### CODE REVIEW

**Review by shawn320 — COMMENTED** [review]
Tags and filters looking good! Looking nice on mobile as well! However, isn't `Past projects` should be in red instead of gray?

**Comment by var-kyle** [comment]
> 
> 
> Tags and filters looking good! Looking nice on mobile as well! However, isn't `Past projects` should be in red instead of gray?

Good question, I don't see anything in the Figma designs for past projects. I'll ask the designers.

**Comment by shawn320** [comment]
> > Tags and filters looking good! Looking nice on mobile as well! However, isn't `Past projects` should be in red instead of gray?
> 
> Good question, I don't see anything in the Figma designs for past projects. I'll ask the designers.

I see, I didn't check figma, I was looking at the document attached to the card, maybe they changed it but forgot to update the document.

**Comment by var-kyle** [comment]
> 
> 
> > > Tags and filters looking good! Looking nice on mobile as well! However, isn't `Past projects` should be in red instead of gray?
> > 
> > 
> > Good question, I don't see anything in the Figma designs for past projects. I'll ask the designers.
> 
> I see, I didn't check figma, I was looking at the document attached to the card, maybe they changed it but forgot to update the document.

You were correct, I just missed that comment in the card.

**Review by shawn320 — APPROVED** [review]
Looks good! Thank you.

**Pull request merged**
