### PR TITLE
Bug/344 error on click

### PR DESCRIPTION
**Pull request by nibivi77**
# Description

[Signup error click](https://trello.com/c/Uo1X4ZYo/344-344-fix-onclick-is-not-a-function-when-user-clicks-on-error-message)

When clicking on an item from the error summary for teh signup form, the app would crash - see Trello board item linked above.

## In This PR

Added the functionality to scroll the user to the desired error.
Added smooth scrolling behaviour to both, the sign up button, and the error summary items.

## Acceptance Criteria

N/A

## Test Instructions

1. `git checkout Bug/344-ErrorOnClick` and `npm run dev`
2.  Navigate to the sign up page.
3.  Scroll all the way down and press on the "Submit" button.
4. See the scrolling animation
5. Press on all 4 of the error items to see where the page is scrolled to.

## Help Requested

- Any constructive feedback is more than welcome!

## Checklist

- [x] Strings use placeholders for translation (No hard coded strings)
- [x] Unit tests have been added/updated

### CODE REVIEW

**Review by will0684 — CHANGES_REQUESTED** [review]
Awesome work 👍 

If you check out Paul's issue here: https://github.com/DTS-STN/Alpha-Site/issues/140

He brings up that we should include **focusing** the element that is scrolled into view as well. Best practice and better a11y that way.

**Comment by nibivi77** [comment]
> Awesome work 
> 
> If you check out Paul's issue here: #140
> 
> He brings up that we should include **focusing** the element that is scrolled into view as well. Best practice and better a11y that way.

**Comment by nibivi77** [comment]
> Awesome work 
> 
> If you check out Paul's issue here: #140
> 
> He brings up that we should include **focusing** the element that is scrolled into view as well. Best practice and better a11y that way.

Addressed in the previous commits.

**Review by var-kyle — CHANGES_REQUESTED** [review]
When clicking on an item in the error box, can you make it so that the focus is put on the input of the linked error? Currently the focus remains on the the list of errors so pressing Tab scrolls the page back to the top.

**Comment by nibivi77** [comment]
> When clicking on an item in the error box, can you make it so that the focus is put on the input of the linked error? Currently the focus remains on the the list of errors so pressing Tab scrolls the page back to the top.

Good catch, I will work on this!

**Pull request closed without merging**
