### PR TITLE
Added privacy page, added link to page from signup

### PR DESCRIPTION
**Pull request by krischarbonneau**
# Description

[Create Privacy Policy page with content](https://trello.com/c/sSQRTIpt)

Added the Privacy Policy page and changed the current link on the signup page so it links to this page. Also added the proper opacity values to the safelist for the color contrast PR so the `List` component works properly.

## Acceptance Criteria

Implement the Privacy Policy page as per Figma designs

## Test Instructions

1. Pull in branch
2. Type `npm run dev`
3. Navigate to the Signup page
4. Click `Read the full privacy policy` to go to the Privacy Policy page

## Checklist

- [x] Strings use placeholders for translation (No hard coded strings)
- [x] Unit tests have been added/updated

## Product and Sprint Backlog

[Trello](https://trello.com/b/ZqWtJSyh/alpha-site-board)

### CODE REVIEW

**Review by EphraimAssi — CHANGES_REQUESTED** [review]
Looks good overall but just one small change, for the Experience@servicecanada.gc.ca, it doesn't have a href attribute. You can use the env variable, so basically something like this
 href={`mailto: ${process.env.NEXT_PUBLIC_NOTIFY_REPORT_A_PROBLEM_EMAIL}`}

**Review by EphraimAssi — COMMENTED** [review]
Sorry I just saw something else, at the bottom of the signup page, there's a second "Read the full privacy policy" link and it seems to link to the canada.ca one.

**Comment by krischarbonneau** [comment]
> Sorry I just saw something else, at the bottom of the signup page, there's a second "Read the full privacy policy" link and it seems to link to the canada.ca one.

Whoops, not sure how I missed that, thanks. Fixed now.

**Review by EphraimAssi — APPROVED** [review]
Looks good!

**Pull request merged**
