### PR TITLE
Feature/#131 experiment page

### PR DESCRIPTION
**Pull request by nibivi77**
# Description

[#131 Create an "experiments" page](https://trello.com/c/dAttS8w6/131-131-create-an-experiments-page)

Matching the Experiments page from the Mock-ups.

**Desktop:**
image

**Mobile (below 768px):**
image

## Acceptance Criteria

The content for the landing page is in place, it looks good on large screens and on mobile, and it matches the Figma mockups.

## Test Instructions

1. Go to branch name: Feature/#131-ExperimentPage
2. git pull **and** npm run dev
3. Navigate to the Experiments page from the top nav menu.
4. Analyse the placements of the fake experiments from different screen sizes.

## Help Requested

 - Please analyse the code. I inserted a list of experiments inside the experiments page. Is this how we want to take care of it in the future?
 - Any feedback is greatly appreciated
 - I know there are hard-coded lorem ipsum for placeholders, thus the checkbox below is not checked.
 - Any tests need to be added?

## Checklist

- [ ] Strings use placeholders for translation (No hard coded strings)
- [x] Unit tests have been added/updated

## Product and Sprint Backlog

[#131 Create an "experiments" page](https://trello.com/c/dAttS8w6/131-131-create-an-experiments-page)

### CODE REVIEW

**Comment by nibivi77** [comment]
> This pull request **introduces 1 alert** when merging [43bbd0a](https://github.com/DTS-STN/Alpha-Site/commit/43bbd0af11e74f17f4ec3f5906820ab7f4df7288) into [9337722](https://github.com/DTS-STN/Alpha-Site/commit/9337722478ce81cab3287d0e040d554d5c5eab02) - [view on LGTM.com](https://lgtm.com/projects/g/DTS-STN/Alpha-Site/rev/pr-2031638b67305358a5cca2e37315626b654b97bd)
> 
> **new alerts:**
> 
> * 1 for Unused variable, import, function or class

The variable not used is the setExperimentList hook. It will be used in the future if we are getting the list of experiments from somewhere else.

**Review by EphraimAssi — COMMENTED** [review]
Hey Ben, looks good!

I only found a few things but I don't know if it involves this PR or not, the page can have some padding between the titles and the cards but maybe it's more when those elements are going to be there. As for testing, we don't have cypress testing for the experiments page yet.

**Comment by will0684** [comment]
> > This pull request **introduces 1 alert** when merging [43bbd0a](https://github.com/DTS-STN/Alpha-Site/commit/43bbd0af11e74f17f4ec3f5906820ab7f4df7288) into [9337722](https://github.com/DTS-STN/Alpha-Site/commit/9337722478ce81cab3287d0e040d554d5c5eab02) - [view on LGTM.com](https://lgtm.com/projects/g/DTS-STN/Alpha-Site/rev/pr-2031638b67305358a5cca2e37315626b654b97bd)
> > **new alerts:**
> > 
> > * 1 for Unused variable, import, function or class
> 
> The variable not used is the setExperimentList hook. It will be used in the future if we are getting the list of experiments from somewhere else.

Because the pages are statically generated and should only be retrieving the data once (when the site is built), we shouldn't need any state management on the pages. Just get the data with getStaticProps, and then pass that into/map to the needed components.

**Comment by Moro-Code** [comment]
> > This pull request **introduces 1 alert** when merging [43bbd0a](https://github.com/DTS-STN/Alpha-Site/commit/43bbd0af11e74f17f4ec3f5906820ab7f4df7288) into [9337722](https://github.com/DTS-STN/Alpha-Site/commit/9337722478ce81cab3287d0e040d554d5c5eab02) - [view on LGTM.com](https://lgtm.com/projects/g/DTS-STN/Alpha-Site/rev/pr-2031638b67305358a5cca2e37315626b654b97bd)
> > **new alerts:**
> > 
> > * 1 for Unused variable, import, function or class
> 
> The variable not used is the setExperimentList hook. It will be used in the future if we are getting the list of experiments from somewhere else.

Hmmmm I think we're gonna statically generate the experiments list using getStaticProps. So not sure if this hook will actually be used

**Comment by nibivi77** [comment]
> Hey Ben, looks good!
> 
> I only found a few things but I don't know if it involves this PR or not, the page can have some padding between the titles and the cards but maybe it's more when those elements are going to be there. As for testing, we don't have cypress testing for the experiments page yet.

Padding has been fixed. Let me know if you find something else! :)

**Comment by nibivi77** [comment]
> > > This pull request **introduces 1 alert** when merging [43bbd0a](https://github.com/DTS-STN/Alpha-Site/commit/43bbd0af11e74f17f4ec3f5906820ab7f4df7288) into [9337722](https://github.com/DTS-STN/Alpha-Site/commit/9337722478ce81cab3287d0e040d554d5c5eab02) - [view on LGTM.com](https://lgtm.com/projects/g/DTS-STN/Alpha-Site/rev/pr-2031638b67305358a5cca2e37315626b654b97bd)
> > > **new alerts:**
> > > 
> > > * 1 for Unused variable, import, function or class
> > 
> > 
> > The variable not used is the setExperimentList hook. It will be used in the future if we are getting the list of experiments from somewhere else.
> 
> Because the pages are statically generated and should only be retrieving the data once (when the site is built), we shouldn't need any state management on the pages. Just get the data with getStaticProps, and then pass that into/map to the needed components.

I changed the hook to use getStaticProps. Check it out and let me know if I should improve with anything :)

**Review by will0684 — APPROVED** [review]
I merged the most recent changes from main and its working and looking good. Thanks Ben!

**Review by pcraig3 — APPROVED** [review]

**Pull request merged**
