### PR TITLE
remove ts

### PR DESCRIPTION
**Pull request by Fbasham**
TypeScript is literally only being used for one file: `middleware.ts`.  Either we go all in on TS and convert everything, or we remove TS altogether as a dependency and stick with JS.

### CODE REVIEW

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-1470365791.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-1470365791.azurewebsites.net

**Comment by andr0272** [comment]
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-1470365791.azurewebsites.net

**Review by will0684 — APPROVED** [review]
👍 Good call!

**Pull request merged**
